### ISSUE TITLE
never-ending pipe which results in never-ending task - no loop 'end' flag?

### ISSUE THREAD

**Issue by eliwilliamson** [catdad/gulp-each#3]
just keeps going, and going, and going - it seems like there is not end flag or return.

```
gulp.task("the-task", (cb) => {

  var abspath, subdir, filename;

  gulp.src("src-path")
    .pipe(each(function(content, file, callback) {
      abspath   = S(file.path).chompLeft(file.cwd + "/").s;
      filename  = path.basename(file.path);
      subdir    = S(file.path).chompLeft(file.cwd + "/src-path/").chompRight("/" + filename).s;

      var processedFiles = processFile(abspath, subdir, filename);

      callback(null, processedFiles);
    }));

    var processFile = function() {...}

    cb();
});
```

Thanks for building this plugin and thanks in advance for helping me utilize it to it's fullest potential!

**Comment by catdad** [comment]
Can you tell me more about what you are trying to do? I am not familiar with what `S` is, nor what `processFile` is. And not only that, but you are calling gulp's `cb` immediately, ignoring the stream entirely.

**Comment by catdad** [comment]
Wait, is your question really how do you tell when the `each` iterator is done going through all the files?

**Comment by eliwilliamson** [comment]
I apologize, 's' is stringify - it converts the parameters to a string, 'processfile' is a function that takes the parameters passed to it and extracts info into an array (which is what's returned). In regards to 'cb' ending the task early, can you elaborate? I'm newer to gulp and am trying to port a gruntfile to gulp - been hung up on your each plugin for like 3 days now haha - didn't want to bother you until I'd exhausted every possible hangup but it seems I am still stuck.

**Comment by catdad** [comment]
Well, gulp is based entirely on streams. You've probably seen from the docs how multiple streams get piped into each other...

``` javascript
gulp.src('my/source/**')
  .pipe(doThingOne())
  .pipe(doThingTwo())
  .pipe(gulp.dest('my/destination'))
```

The whole point of this is exactly to "keep going". Each individual "plugin" is a transform stream.

Since you really didn't actually tell me what you are trying to do (everyone always ignored the first question... I should stop asking multiple questions at the same time), I will assume that what you are trying to do is figure out when the processing of all of your files has ended, and you can call the callback of your gulp task. You can do that as such:

``` javascript
gulp.task("the-task", (cb) => {

  var abspath, subdir, filename;

  // please declare your functions before using them
  var processFile = function() {...}

  gulp.src("src-path")
    .pipe(each(function(content, file, callback) {
      abspath   = S(file.path).chompLeft(file.cwd + "/").s;
      filename  = path.basename(file.path);
      subdir    = S(file.path).chompLeft(file.cwd + "/src-path/").chompRight("/" + filename).s;

      var processedFiles = processFile(abspath, subdir, filename);

      callback(null, processedFiles);
    })).on('end', cb);

});
```

And again, I'd be happy to help if you tell me what you actually trying to do.

**Comment by eliwilliamson** [comment]
sorry, i thought i hit all the questions (don't stop asking - you're 💯 ). i am trying to index all files in a directory to be utilized by lunr.js (search tool). perhaps it would be easier to look at the functional gruntfile that i am trying to port (forgive me if it isn't the cleanest organization).

```
var yaml = require("yamljs");
var S = require("string");

var CONTENT_PATH_PREFIX = "site/content";

// must run `npm run build` first to index
var MARKETING_PATH_PREFIX = "dist";

module.exports = function(grunt) {

    grunt.registerTask("lunr-index", function() {

        grunt.log.writeln("Build pages index");

        var indexPages = function() {
            var pagesIndex = []

            grunt.file.recurse(CONTENT_PATH_PREFIX, function(abspath, rootdir, subdir, filename) {
                if (filename.charAt(0) != '.') {
                  grunt.verbose.writeln("Parse file:", abspath);
                  pagesIndex.push(processFile(abspath, subdir, filename));
                }
            });

            grunt.file.recurse(MARKETING_PATH_PREFIX, function(abspath, rootdir, subdir, filename) {
                var ignores = [
                    'css',
                    'js',
                    'xml',
                    'blog',
                    'docs',
                    'tags',
                    'thanks',
                    'img'
                ],
                isRestricted = false;

                if (ignores.some(function(v) { return abspath.indexOf(v) >= 0; })) {
                    isRestricted = true;

                    return isRestricted;
                }

                if (filename.charAt(0) != '.' && filename.charAt(0) != '_' && isRestricted === false) {
                  grunt.verbose.writeln("Parse file:", abspath);
                  pagesIndex.push(processFile(abspath, subdir, filename));
                }
            });

            return pagesIndex;
        };

        var processFile = function(abspath, subdir, filename) {
            var pageIndex;

            if (S(filename).endsWith(".html")) {
                pageIndex = processHTMLFile(abspath, subdir, filename);
            } else {
                pageIndex = processMDFile(abspath, subdir, filename);
            }

            return pageIndex;
        };

        var processHTMLFile = function(abspath, subdir, filename) {
            var content     = grunt.file.read(abspath),
                thisSection = subdir,
                href        = S(abspath).chompLeft(CONTENT_PATH_PREFIX).s,
                pageName    = S(abspath).chompLeft(CONTENT_PATH_PREFIX + "/").chompRight("/index.html").s;

            // if marketing site, put in 'pages' section and trim prefix for `href`
            if (abspath.indexOf(MARKETING_PATH_PREFIX) !== -1) {
                thisSection = "pages"
                href        = S(abspath).chompLeft(MARKETING_PATH_PREFIX).s
                pageName    = S(abspath).chompLeft(MARKETING_PATH_PREFIX + "/").chompRight("/index.html").s;
            }

            // if landing page, title it 'Homepage'
            if (pageName === "index.html") {
                pageName = "Homepage"
            }

            return {
                section: thisSection,
                title: pageName,
                href: href,
                content: S(content).trim().stripTags().stripPunctuation().s
            };
        };

        var processMDFile = function(abspath, subdir, filename) {
            var content = grunt.file.read(abspath);
            var pageIndex;
            // First separate the Front Matter from the content and parse it
            console.log(abspath)
            content = content.split("---");
            var frontMatter;
            try {
                frontMatter = yaml.parse(content[1].trim());
            } catch (e) {
                conzole.failed(e.message);
            }

            if (frontMatter.url) {
                var href = frontMatter.url;
            } else {
                var href = S(abspath).chompLeft(CONTENT_PATH_PREFIX).chompRight(".md").s;
            }
            // href for index.md files stops at the folder name
            if (filename === "index.md") {
                href = S(abspath).chompLeft(CONTENT_PATH_PREFIX).chompRight(filename).s;
            }

            // Build Lunr index for this page
            pageIndex = {
                section: subdir,
                title: frontMatter.title,
                tags: frontMatter.tags,
                href: href,
                content: S(content[2]).trim().stripTags().stripPunctuation().s
            };

            return pageIndex;
        };

        grunt.file.write("site/static/js/lunr/PagesIndex.json", JSON.stringify(indexPages()));
        grunt.log.ok("Index built");
    });
};
```

**Comment by catdad** [comment]
Haha, sorry, I meant what are you trying to do, in English.

It looks like you need to read all of your files, do... something to them, and then... output something? Are you outputting anything? Are you outputting a single json file that is a summary of all the files you read?

**Comment by eliwilliamson** [comment]
You hit the nail on the head. That is precisely what I'm doing in the grunt file and trying to do in the gulp file. The hangup is that I need to perform my tasks synchronously. the task which includes the gulp-each plugin is not ending which prevents me from continuing to the next task in the queue.

**Comment by catdad** [comment]
So... a few things.

First, this module really isn't what you are looking for. You could make it work, but it is not best suited for it. You really want a `reduce` plugin, but I could not actually find a good one. The several that exist all seem to be poor implementations, or completely different things altogether but calling themselves `reduce`. I am writing one now, but it will be a day or two before I have time to finish it.

Second, I mentioned above how you know that it has ended.

Third, another issue you will run into is that in your code above, you are writing an object to a callback that takes a string. This will cause an error. So even if you add a listener for the end of the stream, that end will never happen because it will error. This is partly the reason why you want a `reduce` instead of a an iterator or a `map` (this module is actually `map`, even though it is called each... which is unfortunate).

You can do something like this... which isn't great, but it will work:

``` javascript
var fs = require('filesystem');

gulp.task("the-task", (cb) => {

  var pageIndexes = [];
  var abspath, subdir, filename;

  var processFile = function() {...}

  gulp.src("src-path")
    .pipe(each(function(content, file, callback) {
      abspath   = S(file.path).chompLeft(file.cwd + "/").s;
      filename  = path.basename(file.path);
      subdir    = S(file.path).chompLeft(file.cwd + "/src-path/").chompRight("/" + filename).s;

      var processedFile = processFile(abspath, subdir, filename);

      pageIndexes.push(processedFile);

      callback(null, '');
    })).on('end', function () {
        fs.writeFile('path/to/file.json', JSON.stringify(pageIndexes), cb);
    }).on('error', cb);
});
```

Note also that in your grunt code, you are using a grunt utility to read the file from disk. You don't have to do that in gulp, as it already reads it for you. The `content` variable in the iterator is the text contents of the file, so you can go ahead and use it instead of reading it from disk a second time.

**Comment by catdad** [comment]
In case you are interested in not using the hacky version above, [the `reduce` module I was writing](https://github.com/catdad/gulp-reduce-async) is public now. It comes with an example of doing pretty much exactly what you want (minus the actual processing code... but you have that already).
