### ISSUE TITLE
tasks did not complete

### ISSUE THREAD

**Issue by samogot** [catdad/gulp-each#8]
I'm trying to read contents of all *.json into a global variable `data`
```
[15:23:02] The following tasks did not complete: pug-data
[15:23:02] Did you forget to signal async completion?
```
my task is:
```JavaScript
const data = {}
gulp.task('pug-data', () =>
	gulp.src('./app/data/*.json')
		.pipe($.each((content, file) => {
			data[file.basename] = JSON.parse(content);
		}))
);
```
I also tried with callback
```JavaScript
const data = {}
gulp.task('pug-data', cb =>
	gulp.src('./app/data/*.json')
		.pipe($.each((content, file) => {
			data[file.basename] = JSON.parse(content);
		}))
		.on('end', cb)
);
```
but the error is still here

**Comment by samogot** [comment]
oh, i found it. I need to call file callback even if i don't modify anything
```JavaScript
gulp.task('pug-data', () =>
	gulp.src('./app/data/*.json')
		.pipe($.each((content, file, cb) => {
			data[file.basename] = JSON.parse(content);
			cb(null, file);
		}))
);
```
you'd rather add this info into documentation

**Comment by catdad** [comment]
Hey. You are right, you have to call the callback... that's just how streams work. This module was meant more for people who want to hack at gulp but do not care to write the 30 lines of code it takes to fully support vinyl streams over and over. I probably should be a bit more thorough in documenting the API. Thanks for your input.
